name: ujikom_jmp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  d_info: ^0.2.2
  d_view: ^0.0.5
  http: ^1.1.0
  google_maps_flutter: ^2.5.3
  camera: ^0.11.0+2
  shared_preferences: ^2.3.1
  sensors_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
